import "../styles/global.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-bg-main text-typo-main">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
